### ISSUE TITLE
Typo in the pyproject.toml files: "Python Devleopers"

### ISSUE THREAD

**Issue by chipx86** [youknowone/python-deadlib#1]
I'm glad to see this project start up! Thanks for your work on this. I'm especially looking forward to NIS support making a comeback, since we have some deeply-legacy environments to support there in our software.

I did notice that the pyproject.toml files were generated with a typo:

```toml
authors = [
    { name = "Python Devleopers", email = "python-deadlib@youknowone.org" }
]
```

"Devleopers" should of course be "Developers".

Thanks again, and best of luck with the project!

**Comment by youknowone** [comment]
Thank you for the report! And I am happy to hear this project is helpful 😄

**Comment by youknowone** [comment]
Oh, you are looking for `nis` module. Because it is a c-implemented module, it will not be distributed by me. It will require additional packaging work for c modules.

**Comment by chipx86** [comment]
I figured that might be the case. We're looking into just shelling out to `yp*` commands to do the work, barring any `nis` alternative appearing (in our case, we don't need much of the `nis` package anyway).

I'd rather just remove NIS support, but it's surprisingly still heavily in use in a number of places.
