### ISSUE TITLE
Distutils testsuite doesn't run in python 3.13

### ISSUE THREAD

**Issue by lucas42** [youknowone/python-deadlib#16]
Running the `distutils` testsuite hits an error in python 3.13.  It looks like some sort of missing test dependencies.

```
E
======================================================================
ERROR: test_distutils (unittest.loader._FailedTest.test_distutils)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_distutils
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.13.0/lib/python3.13/unittest/loader.py", line 137, in loadTestsFromName
    module = __import__(module_name)
  File "/distutils/tests/test_distutils.py", line 8, in <module>
    import distutils.tests
  File "/distutils/distutils/tests/__init__.py", line 18, in <module>
    from test.support import run_unittest, save_restore_warnings_filters
ImportError: cannot import name 'run_unittest' from 'test.support' (/root/.pyenv/versions/3.13.0/lib/python3.13/test/support/__init__.py)


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by lucas42** [comment]
Looks like the methods this test relied on were deliberately removed from python 3.13: https://github.com/python/cpython/blob/44f841f01af0fb038e142a07f15eda1ecdd5b08a/Misc/NEWS.d/3.13.0a2.rst?plain=1#L1163-L1169

Not sure it's worth the effort of getting these the `distutils` tests up and running, given [setuptools](https://setuptools.pypa.io/en/latest/setuptools.html) appears to be the supported replacement.

**Comment by lucas42** [comment]
Oh, looks like the tests also fail in python 3.11 & 3.12: https://github.com/youknowone/python-deadlib/actions/runs/11573017557/job/32214289258

So perhaps it's an issue with the tests themselves, rather than the 3.13 change?

**Comment by youknowone** [comment]
the error message looks like indicating test files were put on wrong place

**Comment by lucas42** [comment]
@youknowone what version of cpython was the `distutils` source code taken from?

I've found this from python 3.11.7 which states that `run_unittest()` was removed from the test.support module:
https://github.com/python/cpython/blob/3.11/Misc/NEWS.d/3.11.7.rst?plain=1#L508-L516

The tests in the version we are using rely on that, but looks like the version in cpython was reworked at some point to not need that function.

**Comment by lucas42** [comment]
Ah, that explains it.  The internal test libraries its tests depend on have been refactored quite a bit then, which explains why the tests are failing.

Do we want to take a newer version of the code (eg after the 3.11.7 refactor)?  I think the tests will be easier to run in that case.

I've also just come across this repository: https://github.com/pypa/distutils which looks to be doing the same thing.  It's specifically for `distutils` and is quite active.  Perhaps easier to point people at that effort, rather than re-doing it here?

**Comment by youknowone** [comment]
I realized I missed distutils from update after 3.9 🙄 
Yes, that need to be updated. The repository looks like to be supposed to be vendored in other projects. That might be true. It could be easier. But let's check about original source first.

**Comment by youknowone** [comment]
let me work on it a bit

**Comment by youknowone** [comment]
it seems it is more complicated than other libraries. Making the tests pass in 3.11 is easy, but not in 3.12.

**Comment by youknowone** [comment]
If it requires too much changes, I think not maintaining and releasing distutils makes sense in this repository. Other projects will take it.

**Comment by youknowone** [comment]
https://peps.python.org/pep-0632/#backwards-compatibility

**Comment by cdce8p** [comment]
I agree, maintenance of `distutils` has been largely taken over by setuptools / PyPA. The initial transition was a bit ruff but those issues are largely resolved now. So there isn't really a need for (another) distutils backport IMO.
