### ISSUE TITLE
Publish updated version of standard-mailcap to pypi

### ISSUE THREAD

**Issue by meeuw** [youknowone/python-deadlib#39]
Hi, could you please publish mailcap from this repository to pypi?

The currently available version of standard-mailcap at pypi doesn't work.

The proposed solution in https://github.com/pazz/alot/issues/1632 is blocked by this.

**Comment by youknowone** [comment]
Hi, it is released just few days ago. If you still experience problem, could you share error messages or a draft PR of alot with CI to use standard-mailcap?

**Comment by meeuw** [comment]
Oh whups, I forgot to check before I created this issue if it was still outdated. Thanks a lot and sorry for bothering.
