### ISSUE TITLE
Dependencies between dead libraries not listed in requires

### ISSUE THREAD

**Issue by lucas42** [youknowone/python-deadlib#5]
Some of the libraries in this repo depend on each other (for example, `aifc` imports `chunk`)

However, the way they are currently built relies on the core python version of those dependencies, rather than pulling in the deadlib version of the dependencies (eg through `requires` in `pyproject.toml`).  This means they won't work in python 3.13 due to [PEP 594](https://peps.python.org/pep-0594/).  Yes, the change this repository is meant to help mitigate actually breaks this repository!

## Impacted libraries
I've had a quick look through the repo to try to find which libraries are impacted.  I've found the following (but may not be complete)

|Library|Dependency|
|---|---|
|aifc|chunk|
|aifc|audioop|
|snhdr|aifc|
|sunau|audioop|

## Tests
At the moment, I don't think the tests pull in dependencies on-the-fly.  So they currently fail on 3.13.

**Comment by youknowone** [comment]
Is this now fully resolved?

**Comment by lucas42** [comment]
I've had another look through whats missing.
Aside from the ones you've added in #15, there's a couple more missing.  I've created separate tickets for them: #19 & #21
So I'll close this ticket given we have separate tickets for the others.
